"""Fix tables

Revision ID: 3e16d1cf4d2c
Revises: 9e2aef680bac
Create Date: 2024-03-26 20:16:46.628481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e16d1cf4d2c'
down_revision: Union[str, None] = '9e2aef680bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
