"""added event_id column to category

Revision ID: 69c95541fc0d
Revises: dc5a7f693302
Create Date: 2024-03-26 16:56:16.391507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c95541fc0d'
down_revision: Union[str, None] = 'dc5a7f693302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'event_id')
    # ### end Alembic commands ###
