"""fix tables

Revision ID: 6e7a3ef48846
Revises: f00a1ebde929
Create Date: 2024-03-20 22:17:22.311878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7a3ef48846'
down_revision: Union[str, None] = 'f00a1ebde929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ticket_count', sa.Integer(), nullable=False))
    op.drop_index('ix_events_ticket', table_name='events')
    op.create_index(op.f('ix_events_ticket_count'), 'events', ['ticket_count'], unique=False)
    op.drop_column('events', 'ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ticket', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_ticket_count'), table_name='events')
    op.create_index('ix_events_ticket', 'events', ['ticket'], unique=False)
    op.drop_column('events', 'ticket_count')
    # ### end Alembic commands ###
