"""Fix tables

Revision ID: 9e2aef680bac
Revises: 69c95541fc0d
Create Date: 2024-03-26 20:07:52.689733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2aef680bac'
down_revision: Union[str, None] = '69c95541fc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_event_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'event_id')
    op.drop_constraint('events_category_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_category_id_fkey', 'events', 'categories', ['category_id'], ['id'])
    op.add_column('categories', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_event_id_fkey', 'categories', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
